### PR TITLE
Add possibility to set projection policy

### PR DESCRIPTION
**Pull request by ritvje**
Add possibility to set projection policy (options `FORCE_DECLARED`,`REPROJECT_TO_DECLARED` or `NONE`) in config with:

```yaml
common_items:
  projection_policy: FORCE_DECLARED # or NONE or REPROJECT_TO_DECLARED

```

The function to set this is a bit hacky, since just setting the `coverage.projection_policy` attribute does not seem to work, most likely due to inconsistent naming in the [geoserver-restconfig object definition](https://github.com/GeoNode/geoserver-restconfig/blob/ca13727991d0b9d520c5ccefc65cf60f6fe6dc51/src/geoserver/resource.py#L229) (attribute name is `projection_policy` but it should be `projectionPolicy` to be written in REST message).

### CODE REVIEW

**Review by lahtinep — APPROVED** [review]
That definitely looks like a bug in the parent library. There are also other properties that use the underscore version instead of camelCase in the `writers` dict: `native_name`, `native_format`, `native_crs`, `default_interpolation_method` and `interpolation_methods. Would maybe make sense to create an issue about asking about these in their GitHub repo.

Do you think this will continue to work if/when they fix the library?

**Comment by ritvje** [comment]
I think if they fix it in the library, we might end up with duplicate entries in the XML argument in the REST call. I'm not sure if that would cause issues or if it would just get ignored.

But thinking now, if we use camelCase for the attribute name, then we would just we overwriting the existing writers and there should not be duplicate entries. I'll commit a fix for that.

**Review by lahtinep — APPROVED** [review]
I don't want to start digging into how the parent library actually handles these properties, but if this works I'm happy with the PR :sweat_smile: 
Any more changes planned, or can we merge?

**Comment by ritvje** [comment]
Let's merge this one.

**Pull request merged**
